### ISSUE TITLE
Setup coverage tests for backend

### ISSUE THREAD

**Issue by EddieTheCubeHead** [EddieTheCubeHead/Stagnum#22]
Agree on a reasonable coverage (100% with liberal use of #pragma? 90%? 75%?). Setup a coverage test as a part of CI/CD pipeline.

Acceptance criteria: coverage tests are a part of the test set with the agreed upon required percentage. Test set passes.

**Comment by tuomasmustakallio** [comment]
100% coverage with # pragma: no cover
