### ISSUE TITLE
Implement login and token functionality to frontend

### ISSUE THREAD

**Issue by EddieTheCubeHead** [EddieTheCubeHead/Stagnum#49]
If client doesn't have a token, home page (all routes? If possible) should reroute to login page.

Once client gets token from login page, all requests should include the token in header "token"

Acceptance criteria: described functionality exists and is tested accoding to front end team standards. Test set passes

**Comment by tuomasmustakallio** [comment]
https://jasonwatmore.com/post/2021/08/30/next-js-redirect-to-login-page-if-unauthenticated

This should be a good start for this ticket for the rerouting. We don't need to have the authentication check from the server at the authCeck-function but a simple token != null or something like that for start which then runs on router events.
