### ISSUE TITLE
Improve port and url handling in the project

### ISSUE THREAD

**Issue by EddieTheCubeHead** [EddieTheCubeHead/Stagnum#76]
Standardize default ports between Docker and local deployments.

Make sure all urls can be set via configurable sources (env variables) and no urls are hard-coded directly into calls.

Subtasks

- [x] #81 
- [x] #82
- [x] #83

Acceptance criteria: all subtasks are completed

**Comment by EddieTheCubeHead** [comment]
.env used for docker confs

**Comment by KeManen** [comment]
Raikka pyorii
